### ISSUE TITLE
Distributie Platformen SOLL NoSQL en RDBMS-sen

### ISSUE THREAD

**Issue by AndreRietveld** [onderwijsarchitectuur/Gegevensmanagement#14]
In View Distributie Platformen SOLL staan in [ABB] Database NoSQL, Triple Store en verschillende merken DBMS naast elkaar. Dit zijn verschillende ordeningen.

Is er een specifieke reden om het op deze manier weer te geven?

**Comment by GeraldGrootRoessink** [comment]
Data wordt op meerdere manieren gerepresenteerd. Of één generieke SQL database. Of gespecialiseerd? Het verhaal is nu gespecialiseerd.
