### ISSUE TITLE
Metadata platform: Gegevensmodellencyclus terug laten komen.

### ISSUE THREAD

**Issue by onderwijsarchitectuur** [onderwijsarchitectuur/Gegevensmanagement#29]
Ik vind het jammer  dat dit een applicatiegerichte view is.  (Meta)gegevens is het hoofdonderwerp. Daarom stel ik voor om functies te verbinden met bedrijfsobjecten (die we grotendeels al hebben onderkend):

1. architectuurmodel (BO+GO)                      AMEFF
2. begrippenkader (of conceptueel model)   SKOS
3. logisch model                                             MIM
4. technisch model                                         OAS3, XSD, oid
5. gegevensartefact                                        DCAT

Hiervoor hebben we DUO tot op zekere hoogte al applicatiecomponenten. Door hierop in te zoomen, zien we waar nog wat moet gebeuren. Dat is architectuur.

1. Sparx
2. Magic Draw of iets anders?
3. Magic Draw
4. Magic Draw
5. niet bekend

Deze zaken moeten ontsloten worden. Dat is mijns inziens de belangrijkste en meeste urgente uitdaging. We hebben een aantal ontsluitingsmechanismen (lees interface) nodig naar een in te richten federatieve datacatalogus:

1. Semantische wiki
2. Business Glossary Thesaurus (datacatalogus level 1) ,  waarover gaat het?
3. Data catalogus level 2                                                ,  wat is het?
4. Data catalogus level 3                                                ,  hoe gepresenteerd?
5. Data catalogus level 4                                                ,  waar is het?

Verder:
- Deze vormen van business metadata (en modellen) ontstaan in de systeemontwikkeling, Het is belangrijk dat de gaten en kieren in dat proces worden gedicht. Alles wat daarbij kan helpen is waardevol. Misschien iets met AI? 
- De logger en collector schaar ik in een andere hoek technische of operationele metadata. Sorrie maar dat staat wat mij betreft niet op het menu..

**Comment by GeraldGrootRoessink** [comment]
Is opgelost met een nieuwe view
