### ISSUE TITLE
Distributie platformen SOLL

### ISSUE THREAD

**Issue by fennemh** [onderwijsarchitectuur/Gegevensmanagement#8]
Er missen in het algemeen veel omschrijvingen. Architectuur in de blote kont :)

**Comment by GeraldGrootRoessink** [comment]
In description-veld: kan gaan over begrippen (hyperlink) of een omschrijving. Volgende keer bespreken.

**Comment by fennemh** [comment]
Fijn dat er omschrijvingen zijn toegevoegd.
